# Paths are relative to the directory that holds this configuration file.

[tempest]
User = "sandstorm"
Group = "sandstorm"

[build-tool]
# DownloadDirTemplate supports the Home template variable, i.e., {{ .Home }}
# will expand to the current user's home directory.
DownloadDirTemplate = "{{ .Home }}/.cache/tempest-build-tool/downloads"

DownloadUserAgent = "tempest-build-tool"

# ToolChainDirTemplate supports the Home template variable.
ToolChainDirTemplate = "toolchain"

[build-tool.bison]
# Use DownloadUrl to override the DownloadUrlTemplate in downloads.toml.
#DownloadUrl = "https://ftpmirrors.gnu.org/bison/bison-3.18.2.tar.xz"

# Use Executable to specify the path to an existing Bison executable.
#Executable = "/usr/local/bin/bison"

# Use Version to override the PreferredVersion in downloads.toml.
#Version = "3.18.2"

[build-tool.bpf_asm]
# bpf_asm is a tool from the Linux kernel.  To configure downloads of the Linux
# kernel, see the [build-tool.linux] section.

# Use Executable to specify the path to an existing bpf_asm executable.
#Executable = "/usr/local/bin/bpf_asm"

[build-tool.capnproto]
# Use DownloadUrl to override the DownloadUrlTemplate in downloads.toml.
#DownloadUrl = "https://capnproto.org/capnproto-c++-1.1.0.tar.gz"

# Use Executable to specify the path to an existing capnp executable.
#Executable = "/usr/local/bin/capnp"

# Use Version to override the PreferredVersion in downloads.toml.
#Version = "1.1.0"

[build-tool.flex]
# Use DownloadUrl to override the DownloadUrlTemplate in downloads.toml.
#DownloadUrl = "https://github.com/westes/flex/releases/download/v2.6.4/flex-2.6.4.tar.gz"

# Use Executable to specify the path to an existing Flex executable.
#Executable = "/usr/local/bin/flex"

# Use Version to override the PreferredVersion in downloads.toml.
#Version = "2.6.4"

[build-tool.linux]
# Use DownloadUrl to override the DownloadUrlTemplate in downloads.toml.
#DownloadUrl = "https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.13.8.tar.xz"

# Use Version to override the PreferredVersion in downloads.toml.
#Version = "6.13.8"

[build-tool.tinygo]
# Use DownloadUrl to override the DownloadUrlTemplate in downloads.toml.
#DownloadUrl = "https://github.com/tinygo-org/tinygo/releases/download/v0.37.0/tinygo0.37.0.linux-amd64.tar.gz"

# Use Executable to specify the path to an existing TinyGo executable.
#Executable = "/usr/local/bin/tinygo"

# Use Version to override the PreferredVersion in downloads.toml.
#Version = "0.37.0"
