[binaryen]
DownloadUrlTemplate = "https://github.com/WebAssembly/binaryen/releases/download/version_{{ .Version }}/{{ .Filename }}"
FilenameTemplate = "binaryen-version_{{ .Version }}-{{ .Arch }}-{{ .Os }}.tar.gz"
PreferredVersion = "125"

[binaryen.files."binaryen-version_125-arm64-macos.tar.gz"]
SHA-256 = "28bab047c4ce845c5c1da111222ffee5fafcec0bbedd046ad8b3dcae0fd57076"
Size = 6827261

[binaryen.files."binaryen-version_125-aarch64-linux.tar.gz"]
SHA-256 = "d0382de3c189a7cbb9fdda93e2966f4557f6a00f201e2c4937c27ca01cead4fc"
Size = 103059268

[binaryen.files."binaryen-version_125-x86_64-linux.tar.gz"]
SHA-256 = "7c3bc16599c8274a04d34a504fe4be2047884f900e0e2da2f6fb9cd667183be4"
Size = 106809634

[bison]
DownloadUrlTemplate = "https://ftpmirror.gnu.org/bison/{{ .Filename }}"
FilenameTemplate = "bison-{{ .Version }}.tar.xz"
PreferredVersion = "3.8.2"

[bison.files."bison-3.8.2.tar.xz"]
SHA-256 = "9bba0214ccf7f1079c5d59210045227bcf619519840ebfa80cd3849cff5a5bf2"
Size = 2817324

[capnproto]
DownloadUrlTemplate = "https://capnproto.org/{{ .Filename }}"
FilenameTemplate = "capnproto-c++-{{ .Version }}.tar.gz"
PreferredVersion = "1.1.0"

[capnproto.files."capnproto-c++-1.1.0.tar.gz"]
SHA-256 = "07167580e563f5e821e3b2af1c238c16ec7181612650c5901330fa9a0da50939"
Size = 1768797

[flex]
DownloadUrlTemplate = "https://github.com/westes/flex/releases/download/v{{ .Version }}/{{ .Filename }}"
FilenameTemplate = "flex-{{ .Version }}.tar.gz"
PreferredVersion = "2.6.4"

[flex.files."flex-2.6.4.tar.gz"]
SHA-256 = "e87aae032bf07c26f85ac0ed3250998c37621d95f8bd748b31f15b33c45ee995"
Size = 1419096

[go-capnp]
DownloadUrlTemplate = "https://github.com/capnproto/go-capnp/archive/refs/tags/{{ .Filename }}"
FilenameTemplate = "v{{ .Version }}.tar.gz"
PreferredVersion = "3.1.0-alpha.1"

[go-capnp.files."v3.1.0-alpha.1.tar.gz"]
SHA-256 = "054d04ba4cbdce279c3f251b1df2b2907e5bf6746f4fda958c081bf142eca6c3"
Size = 508859

[linux]
DownloadUrlTemplate = "https://cdn.kernel.org/pub/linux/kernel/v{{ .MajorVersion }}.x/{{ .Filename }}"
filenameTemplate = "linux-{{ .Version }}.tar.xz"
PreferredVersion = "6.13.8"

[linux.files."linux-6.13.5.tar.xz"]
SHA-256 = "283ecb0784f3fbc16dd822fb1d9642e230ec7515ed33f120e551b839f355e6e2"
Size = 148547124

[linux.files."linux-6.13.8.tar.xz"]
SHA-256 = "259afa59d73d676bec2ae89beacd949e08d54d3f70a7f8b0a742315095751abb"
Size = 148581924

[tinygo]
DownloadUrlTemplate = "https://github.com/tinygo-org/tinygo/releases/download/v{{ .Version }}/{{ .Filename }}"
FilenameTemplate = "tinygo{{ .Version }}.linux-{{ .Arch }}.tar.gz"
PreferredVersion = "0.37.0"

[tinygo.files."tinygo0.36.0.linux-amd64.tar.gz"]
SHA-256 = "a593f4930d54ae0f6ed47cfc5804e30e50862dc9d3e3f4fc38b93f2ed65380b5"
Size = 152214324

[tinygo.files."tinygo0.36.0.linux-arm64.tar.gz"]
SHA-256 = "cfda7c99030e0ef6f9d1a25be476044703b45980e6269a24add2139de24ec0fd"
Size = 146673758

[tinygo.files."tinygo0.37.0.linux-amd64.tar.gz"]
SHA-256 = "ff3680acc0e2295db453e8e241a0cab5ea44f84586f4c5c00860822380713397"
Size = 153063689

[tinygo.files."tinygo0.37.0.linux-arm64.tar.gz"]
SHA-256 = "dece4264cef3f553636482c2ba15e04ac4e1597dafc092b27c6e3da3acc4ad73"
Size = 147485005
